version: '3.8'
services:
  app:
    container_name: remind_app_prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 8080:80
    environment:
      - NODE_ENV=production