# Utilisez une image Node.js pour construire votre application
FROM node:14

# Définissez le répertoire de travail dans le conteneur
WORKDIR /app

# Copiez le fichier package.json et package-lock.json dans le conteneur
COPY package*.json ./

# Installez les dépendances de votre application
RUN npm install

# Copiez le reste de votre application dans le conteneur
COPY . .

# Exposez le port sur lequel votre application s'exécute
EXPOSE 3000

# Définissez la commande pour démarrer votre application
CMD ["npm", "run", "dev"]